
import "./globals.css";


export const metadata = {
  title: "Hotel Booking",
  description: "Generated by create Gautam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
